name: wordsapp
services:
  client:
    image: nest-frontend
    platform: linux/amd64
    networks:
      - api-network

  nginx:
    image: nest-nginx
    platform: linux/amd64
    #depends_on:
    #  - client
    networks:
      - api-network

networks:
  api-network:
    name: wordsapp-network
    driver: bridge
