FROM node:20-slim AS deps
LABEL com.janlibal.image.stage="deps" \
      com.janlibal.image.title="wordsapp-frontend" \
      com.janlibal.image.created="2027-08-26" \
      com.janlibal.image.authors="Jan Libal <jan.libal@yahoo.com>"

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
#COPY .yarn .yarn

RUN yarn install --immutable


FROM node:20-slim AS builder
LABEL com.janlibal.image.stage="deps" \
      com.janlibal.image.title="wordsapp-frontend" \
      com.janlibal.image.created="2027-08-26" \
      com.janlibal.image.authors="Jan Libal <jan.libal@yahoo.com>"

WORKDIR /app

RUN corepack enable

COPY --from=deps /app/node_modules ./node_modules
#COPY --from=deps /app/.yarn ./.yarn
COPY --from=deps /app/package.json ./package.json
COPY --from=deps /app/yarn.lock ./yarn.lock
COPY --from=deps /app/.yarnrc.yml ./.yarnrc.yml

COPY . .

ENV NODE_ENV=production

RUN yarn build


FROM node:20-slim AS runner
LABEL com.janlibal.image.stage="deps" \
      com.janlibal.image.title="wordsapp-frontend" \
      com.janlibal.image.created="2027-08-26" \
      com.janlibal.image.authors="Jan Libal <jan.libal@yahoo.com>"

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

USER node

EXPOSE 3000

CMD ["node", "server.js"]
