services:
  client:
    #platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - client-node-modules:/app/node_modules
    expose:
      - '3000'
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
volumes:
  client-node-modules:
    name: client-node-modules
    labels:
      app: nextjs
      env: dev
