FROM node:20-slim
LABEL com.janlibal.image.stage="deps" \
      com.janlibal.image.title="wordsapp-frontend" \
      com.janlibal.image.created="2027-08-26" \
      com.janlibal.image.authors="Jan Libal <jan.libal@yahoo.com>"

WORKDIR /app

RUN corepack enable

# Copy only dependency files first
COPY package.json yarn.lock .yarnrc.yml ./

# If using Yarn Berry, you likely also need:
COPY .yarn .yarn

RUN yarn install

# Don't copy the rest, dev will use blind mount
# COPY . .
COPY next.config.mjs ./next.config.mjs

EXPOSE 3000

ENV NODE_ENV=development

ENV CHOKIDAR_USEPOLLING=true

CMD ["yarn", "dev"]
