'use client'

import type { Metadata } from 'next'
import '../styles/globals.css'
import theme from './theme'
import { ThemeProvider } from '@mui/material/styles'
import Navbar from './components/Navbar'

interface LayoutProps {
  children: React.ReactNode
}

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }: LayoutProps) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </ThemeProvider>
  )
}

/*export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}*/
